### ISSUE TITLE
기본 스테이지 맵 구현

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/ProjectKT#2]
* 간단한 Goal이 있는 맵 구현
* 점프와 이동만으로 클리어 가능해야 하나, 너무 단순하진 않았으면 좋겠음
* 조작에 대하여 충분히 학습이 가능한 정도의 난이도 였으면 좋겠음
* 맵 데이타 어떤 식으로 만들지 정해야 함
* 맵 데이타 만들 툴 만들어야 함

**Comment by Geeko9** [comment]
스테이지01 예시

![image](https://user-images.githubusercontent.com/2485863/34648746-6ddd051c-f3e3-11e7-8bb9-3e3209ecf5c6.png)
